config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    resources :discounts, only: :update
    resource :cart, only: %i(show destroy)
    resources :line_items
    devise_for :users, controllers: { registrations: "registrations" }
    resources :users, only: %i(show) do
      resources :orders, only: :show
    end
    resources :brands, only: %i(show index)
    resources :products, only: %i(show index) do
      resources :comments
    end
    root "static_pages#index"
    post "orders/new", to: "orders#create"
    get "admin", to: "admin#index"
    namespace :admin do
      resources :coupons
      resources :products
      resources :brands
      resources :orders
      resources :users
      resources :static_pages, only: %i(index)
      resources :notifications, only: %i(index update)
    end
    root "static_pages#index"
    resources :orders, except: :destroy
    post "orders/new", to: "orders#create"
    get :search, to: "searches#index"
    resources :products
  #  mount ActionCable.server, at: "/cable"
  end
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true, length: {maximum: Settings.name.maximum}
  scope :desc, ->{order created_at: :desc}
end

app/controllers/admin/brands_controller.rb
module Admin
  class BrandsController < Admin::BaseController
    before_action :find_brand, only: %i(show edit update destroy)

    def index
      @brands = Brand.paginate page: params[:page], per_page: Settings.per_page
    end

    def new
      @brand = Brand.new
    end

    def create
      @brand = Brand.new brand_params

      if brand.save
        notice_redirect
      else
        render :new
      end
    end

    def show
      @products = brand.products.desc.paginate page: params[:page],
        per_page: Settings.per_page
    end

    def edit; end

    def update
      @brand = Brand.find_by id: params[:id]

      if brand.update_attributes brand_params
        flash[:success] = t "brand_updated"
        redirect_to admin_brands_url
      else
        render :edit
      end
    end

    def destroy
      brand.destroy
      flash[:success] = t "brand_deleted"
      redirect_to admin_brands_url
    end

    private

    attr_reader :brand

    def notice_redirect
      flash[:info] = t "created_brand"
      redirect_to admin_brands_url
    end

    def brand_params
      params.require(:brand).permit :name
    end

    def find_brand
      @brand = Brand.find_by id: params[:id]

      return if brand
      flash[:success] = t "failed_brand"
      redirect_to root_path
    end
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  attr_reader :brand

  before_action :find_brand, only: %i(show)

  def index
    @brands = Brand.desc.paginate page: params[:page]
  end

  def show
    @brands = Brand.desc.all
  end

  private

  def find_brand
    @brand = Brand.find_by id: params[:id]

    return if brand
    flash[:success] = t "failed_brand"
    redirect_to root_path
  end
end

app/views/admin/brands/_form.html.erb
<%= form_for [:admin, brand] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label t :name_brand %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/admin/brands/edit.html.erb
<% provide :title, t("edit_brand") %>
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="add-to-cart-button"><%= t "brand" %></div>
    <div class="panel-body"><%= render "form", brand: @brand %></div>
  </div>
</div>

app/views/admin/brands/index.html.erb
<% provide :title, t("brand") %>
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="add-to-cart-button"><%= t "brand" %></div>
    <div class="panel-body">
      <div class="panel-footer">
        <%= link_to t("add_new_brand"), new_admin_brand_path %>
      </div>
      <table class="table table-striped table-hover sortable">
        <thead>
          <tr>
            <th><%= t "name_brand" %></th>
            <th><%= t "quantity" %></th>
          </tr>
        </thead>
        <tbody>
          <% @brands.each do |brand| %>
            <tr>
              <td><%= link_to brand.name, admin_brand_path(brand) %></td>
              <td><%= brand.products.size %> <%= t "product" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="panel-footer"><%= will_paginate @brands %></div>
    </div>
  </div>
</div>

app/views/admin/brands/new.html.erb
<% provide :title, t("new_brand") %>
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="add-to-cart-button"><%= t "brand" %></div>
    <div class="panel-body">
      <%= render "form", brand: @brand %>
    </div>
  </div>
</div>

app/views/admin/brands/show.html.erb
<% provide :title, t("product") %>
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="add-to-cart-button">
      <%= t "product_of" %> <%= @brand.name %>
    </div>
    <div class="panel-body">
      <div class="panel-footer">
        <%= link_to t("add_new_product"),
          new_admin_product_path(brand_id: @brand) %> |
        <%= link_to t("edit_brand"), edit_admin_brand_path(@brand) %> |
        <%= link_to t("delete_brand"), admin_brand_path(@brand),
          method: :delete, data: {confirm: t("are_you_sure")} %>
      </div>
      <%= render "admin/products/index", products: @products %>
    </div>
  </div>
</div>