config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    resources :discounts, only: :update
    resource :cart, only: %i(show destroy)
    resources :line_items
    devise_for :users, controllers: { registrations: "registrations" }
    resources :users, only: %i(show) do
      resources :orders, only: :show
    end
    resources :brands, only: %i(show index)
    resources :products, only: %i(show index) do
      resources :comments
    end
    root "static_pages#index"
    post "orders/new", to: "orders#create"
    get "admin", to: "admin#index"
    namespace :admin do
      resources :coupons
      resources :products
      resources :brands
      resources :orders
      resources :users
      resources :static_pages, only: %i(index)
      resources :notifications, only: %i(index update)
    end
    root "static_pages#index"
    resources :orders, except: :destroy
    post "orders/new", to: "orders#create"
    get :search, to: "searches#index"
    resources :products
  #  mount ActionCable.server, at: "/cable"
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def current_cart? cart
    self == cart
  end

  def add_product product
    product_id = product.id
    line_item = line_items.find_by product_id: product_id

    if (current_item = line_item)
      current_item.quantity += 1
    else
      current_item = line_items.build product_id: product_id
    end
    current_item
  end

  def total_price
    line_items.to_a.sum(&:total_price)
  end

  def remain_price coupon
    return total_price unless coupon
    total_price * (100 - coupon.percent) / 100
  end

  def sale_price coupon
    total_price - remain_price(coupon)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  attr_reader :cart

  before_action :current_cart
  before_action :find_coupon

  def show; end

  def destroy
    cart.line_items.destroy_all
    flash[:success] = "Cart are empty"
    redirect_to root_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
	def set_cart
		@cart = Cart.find_by id: session[:cart_id]

		return if @cart.present?
		@cart = Cart.create
		session[:cart_id] = @cart.id
	end
end

app/views/carts/_discount_input.html.erb
<table>
  <tr>
    <td>
      <div class="form-group has-feedback" >
        <%= text_field_tag :apply, session[:coupon_code],
          class: "form-control", id: "coupon-input", placeholder: t("discout") %>
        <% if session[:coupon_code] %>
          <i class="glyphicon glyphicon-ok
            ok-icon form-control-feedback" ></i>
        <% end %>
      </div>
    </td>
    <td>
      <button class="btn btn-success" id="discount">
        <%= t "apply" %>
      </button>
    </td>
  </tr>
</table>

app/views/carts/_list_item.html.erb
<div class="col-md-8">
  <div class="features-items">
    <h2 class="title text-center"><%= t "product" %></h2>
  </div>
  <table class="shop-table cart">
    <thead>
      <tr>
        <th><%= t "image" %></th>
        <th><%= t "product" %></th>
        <th><%= t "quantity" %></th>
        <th><%= t "price" %></th>
        <th><%= t "total" %></th>
        <th><%= t "remove" %></th>
      </tr>
    </thead>
    <tbody>
      <% cart.line_items.each do |item| %>
        <tr class="cart_item" id=<%= item.id %>>
          <td class="product-thumbnail">
            <%= image_tag item.product.image_url %>
          </td>
          <td class="product-name">
            <%= link_to item.product.name, item.product %>
          </td>
          <td>
            <div class="quantity buttons_added">
              <%= link_to "+", line_item_path(item.id, method: "line_items"),
                class: "minus", method: :patch, remote: true %>
               <input type="number" size="4"
                value="<%= item.quantity %>" readonly>
              <%= link_to "-", line_item_path(item.id, method: "decrease"),
                class: "minus", method: :patch, remote: true %>
            </div>
          </td>
          <td>
            <span class="amount">
              <%= number_to_currency item.product.price %>
            </span>
          </td>
          <td>
            <span class="amount">
              <%= number_to_currency item.total_price %>
            </span>
          </td>
          <td class="product-remove">
            <%= link_to item, method: :delete, remote: true,
              data: {confirm: t("are_you_sure")},
              class: "btn btn-danger" do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/carts/_total_price.html.erb
<table>
  <tbody>
    <tr class="order-total">
      <th><%= t "current" %></th>
      <td>
        <strong>
          <span class="amount" id="cart_price">
            <%= number_to_currency cart.total_price %>
          </span>
        </strong>
      </td>
    </tr>
    <% if coupon %>
      <tr class="order-total">
        <th><%= t "sale" %></th>
        <td>
          <strong>
            <span class="amount" id="cart_price">
              - <%= number_to_currency cart.sale_price(coupon) %>
            </span>
          </strong>
        </td>
      </tr>
      <tr class="order-total">
        <th><%= t "total" %></th>
        <td>
          <strong>
            <span class="amount" id="cart_price">
              <%= number_to_currency cart.remain_price(coupon) %>
            </span>
          </strong>
        </td>
      </tr>
    <% else %>
      <tr class="order-total">
        <th><%= t "total" %></th>
        <td>
          <strong>
            <span class="amount" id="cart_price">
              <%= number_to_currency cart.total_price %>
            </span>
          </strong>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/carts/show.html.erb
<% provide :title, t("cart") %>
<div class="container">
  <div class="row">
    <% if @cart.nil? | @cart.line_items.empty? %>
      <div class="fixed-footer-bottom">
        <div class="col-md-12">
          <div class="features-items">
            <h2 class="title text-center"><%= t "don_have_item" %></h2>
          </div>
        </div>
      </div>
    <% else %>
      <div id="list_item" %>
        <%= render "list_item", cart: @cart %>
      </div>
      <div class="col-md-4">
        <div class="features-items">
          <h2 class="title text-center"><%= t "order" %></h2>
        </div>
        <div class="cart-totals">
          <div id="total_price">
            <%= render "total_price", cart: @cart, coupon: @coupon %>
          </div>
          <%= render "discount_input", cart: @cart %>
        </div>
        <%= link_to new_order_path, class: "submit" do %>
          <span class="glyphicon glyphicon-play"></span>
          <%= t "checkout" %>
        <% end %>
        <br /><br />
        <%= link_to cart_path, method: :delete, data: {confirm: t("are_you_sure")},
          class: "submit" do %>
          <%= t "remove_all_product" %>
        <% end %>
        <br /><br />
        <%= link_to t("back_to_home_to_continue_shopping"),
          root_path, class: "submit" %>
      </div>
    <% end %>
  </div>
</div>