config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    resources :discounts, only: :update
    resource :cart, only: %i(show destroy)
    resources :line_items
    devise_for :users, controllers: { registrations: "registrations" }
    resources :users, only: %i(show) do
      resources :orders, only: :show
    end
    resources :brands, only: %i(show index)
    resources :products, only: %i(show index) do
      resources :comments
    end
    root "static_pages#index"
    post "orders/new", to: "orders#create"
    get "admin", to: "admin#index"
    namespace :admin do
      resources :coupons
      resources :products
      resources :brands
      resources :orders
      resources :users
      resources :static_pages, only: %i(index)
      resources :notifications, only: %i(index update)
    end
    root "static_pages#index"
    resources :orders, except: :destroy
    post "orders/new", to: "orders#create"
    get :search, to: "searches#index"
    resources :products
  #  mount ActionCable.server, at: "/cable"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  has_many :comments, dependent: :destroy
  has_many :line_items, dependent: :destroy
  has_many :item_photos, dependent: :destroy

  validates :brand, presence: true
  validates :name, presence: true, length: {maximum: Settings.name.maximum}
  validates :price, presence: true, numericality: {only_integer: true}
  validates :description, presence: true

  accepts_nested_attributes_for :item_photos,
    reject_if: :all_blank, allow_destroy: true

  mount_uploader :image, ImageUploader

  scope :desc, ->{order created_at: :desc}
  scope :most_bought, (lambda do |_|
    joins("INNER JOIN products ON products.id = product_id")
    .from(LineItem.select("product_id, COUNT(product_id) as count")
    .where.not(order_id: nil).group("product_id")
    .order("count DESC").limit(Settings.ten))
  end)
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::BaseController
    before_action :find_product, only: %i(show edit update destroy)
    before_action :find_brand, only: :new

    def index
      @products = Product.desc.paginate page: params[:page],
        per_page: Settings.per_page
    end

    def new
      @product =
        if brand
          brand.products.new
        else
          Product.new
        end
    end

    def create
      @product = Product.new product_params

      if product.save
        flash[:success] = t "product_created"
        redirect_to admin_products_path
      else
        render :new
      end
    end

    def show; end

    def edit; end

    def update
      if product.update_attributes product_params
        flash[:success] = t "product_updated"
        redirect_to admin_products_path
      else
        render :edit
      end
    end

    def destroy
      product.destroy
      flash[:success] = t "product_deleted"
      redirect_to request.referer || root_path
    end

    private

    attr_reader :product, :brand

    def find_brand
      @brand = Brand.find_by id: params[:brand_id]

      return if brand
      Product.new
    end

    def product_params
      params.require(:product).permit :available, :name,
        :description, :image, :price, :brand_id, :remove_image,
        item_photos_attributes: %i(id product_id photo _destroy)
    end

    def find_product
      @product = Product.find_by id: params[:id]

      return if product
      flash[:success] = t "failed_product"
      redirect_to root_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  attr_reader :product

  before_action :find_product, only: :show
  before_action :all_brands, only: %i(index show)

  def index
    @products = Product.desc.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def show
    @support_comment = SupportComment.new product: product, page: params[:page]
  end

  private

  def all_brands
    @brands = Brand.desc.all
  end

  def find_product
    @product = Product.find_by id: params[:id]

    return if product
    flash[:success] = t "failed_product"
    redirect_to root_path
  end
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, product], html: {multipart: true} do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label t :name_product %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label t :available %>:<br />
  <%= f.check_box :available %> <%= t :available? %><br />

  <%= f.label t :price %>
  <%= f.number_field :price, class: "form-control" %>

  <%= f.label t :description %>
  <%= f.cktext_area :description, placeholder: t("compose_new_micropost") %>

  <%= f.label :avatar %><br>
  <%= f.file_field :image %><br />

  <% if f.object.image? %>
    <%= image_tag f.object.image_url, class: "thumb" %>
    <%= f.check_box :remove_image %><%= t "remove_avatar" %>
  <% end %><br />

  <%= f.label :photo %><br />
  <%= f.fields_for :item_photos do |p| %>
    <div class="field">
      <%= render "image_fields", f: p %>
    </div>
  <% end %>

  <div class="links">
    <%= link_to_add_association t("add_image"), f, :item_photos , partial: "image_fields" %>
  </div>

  <%= f.label :brand %><br />
  <%= f.select :brand_id,
    Brand.all.collect {|brand| [brand.name, brand.id]},
    prompt: t("select") %><br /><br />

  <%= f.submit class: "btn btn-primary" %>
  <% end %>

app/views/admin/products/_image_fields.html.erb
<div class="nested-fields">
  <% if f.object.photo? %>
    <%= image_tag f.object.photo_url, class: "thumb" %>
    <%= link_to_remove_association t("remove_image"), f %>
  <% end %>
  <%= f.file_field :photo %>
</div>

app/views/admin/products/_index.html.erb
<table class="table table-striped table-hover sortable">
  <thead>
    <tr>
      <th><%= t "name_product" %></th>
      <th><%= t "name_brand" %></th>
      <th><%= t "price" %></th>
    </tr>
  </thead>
  <tbody>
    <% products.each do |product| %>
      <tr>
        <td><%= link_to product.name, admin_product_path(product) %></td>
        <td><%= link_to product.brand.name, product.brand %></td>
        <td><%= number_to_currency product.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="panel-footer"><%= will_paginate products %></div>

app/views/admin/products/edit.html.erb
<% provide :title, t("edit_product") %>
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="add-to-cart-button"><%= t "product" %></div>
    <div class="panel-body">
      <%= render "form", product: @product, new_product: @new_product %>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<% provide :title, t("product") %>
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="add-to-cart-button"><%= t "product" %></div>
    <div class="panel-body">
      <div class="panel-footer">
        <%= link_to t("add_new_product"), new_admin_product_path %>
      </div>
      <%= render "index", products: @products %>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<% provide :title, t("new_product") %>
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="add-to-cart-button"><%= t "product" %></div>
    <div class="panel-body">
      <%= render "form", product: @product, new_product: @new_product %>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<% provide :title, @product.name %>
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="add-to-cart-button">
      <%= t "product" %>: <%= @product.name %>
    </div>
    <div class="panel-body">
      <table class="table table-striped table-hover">
        <tr>
          <th><%= t "name_product" %></th>
          <th><%= t "name_brand" %></th>
          <th><%= t "available" %></th>
          <th><%= t "price" %></th>
          <th><%= t "option" %></th>
        </tr>
        <tr>
          <td><%= link_to @product.name, @product %></td>
          <td><%= link_to @product.brand.name, @product.brand %></td>
          <td><%= @product.available? ? t("stock") : t("out_of_stock") %></td>
          <td><%= number_to_currency @product.price %></td>
          <td>
            <%= link_to t("edit"), edit_admin_product_path(@product) %> |
            <%= link_to t("delete"), admin_product_path(@product),
              method: :delete, data: {confirm: t("are_you_sure")} %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>