config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    resources :discounts, only: :update
    resource :cart, only: %i(show destroy)
    resources :line_items
    devise_for :users, controllers: { registrations: "registrations" }
    resources :users, only: %i(show) do
      resources :orders, only: :show
    end
    resources :brands, only: %i(show index)
    resources :products, only: %i(show index) do
      resources :comments
    end
    root "static_pages#index"
    post "orders/new", to: "orders#create"
    get "admin", to: "admin#index"
    namespace :admin do
      resources :coupons
      resources :products
      resources :brands
      resources :orders
      resources :users
      resources :static_pages, only: %i(index)
      resources :notifications, only: %i(index update)
    end
    root "static_pages#index"
    resources :orders, except: :destroy
    post "orders/new", to: "orders#create"
    get :search, to: "searches#index"
    resources :products
  #  mount ActionCable.server, at: "/cable"
  end
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  validate :invalid_expire_date, :invalid_coupon
  validates :code, presence: true, length: {minimum: Settings.code.minimum}
  validates :percent, presence: true,
    numericality: {less_than: Settings.percent.maximum,
                   greate_than: Settings.percent.minimum}
  validates :import, numericality: {greate_than: Settings.import.minimum},
    allow_nil: true

  scope :desc, ->{order created_at: :desc}

  def unexpired?
    expire ? expire > Time.zone.now : true
  end

  def unfull_import?
    import ? import > imported : true
  end

  private

  def invalid_expire_date
    return if expire.blank? || Time.zone.now < expire
    errors.add :expire, I18n.t("invalid_date")
  end

  def invalid_coupon
    return unless expire.blank? && import.blank?
    errors.add :coupon, I18n.t("invalid_coupon")
  end
end

app/controllers/admin/coupons_controller.rb
module Admin
  class CouponsController < Admin::BaseController
    before_action :find_coupon, except: %i(index new create)

    def index
      @coupons = Coupon.desc.paginate page: params[:page]
    end

    def new
      @coupon = Coupon.new
    end

    def create
      @coupon = Coupon.new coupon_params

      if coupon.save
        flash[:success] = t "created_coupon"
        redirect_to admin_coupons_path
      else
        render :new
      end
    end

    def show; end

    def edit; end

    def update
      if coupon.update_attributes coupon_params
        flash[:success] = t "updated_coupon"
        redirect_to admin_coupons_path
      else
        render :edit
      end
    end

    def destroy
      coupon.destroy
      unsuccess_destroy
    end

    private

    attr_reader :coupon

    def coupon_params
      params.require(:coupon).permit :code, :expire, :import, :percent
    end

    def find_coupon
      @coupon = Coupon.find_by id: params[:id]

      return if coupon
      flash[:errors] = t "not_found_coupon"
      redirect_to root_path
    end

    def unsuccess_destroy
      flash[:danger] = t "not_exist_coupon"
      redirect_to admin_coupons_path
    end
  end
end

app/views/admin/coupons/_form.html.erb
<%= form_for [:admin, coupon] do |f| %>
  <%= render "shared/error_messages", object: coupon %>

  <div class="form-group">
    <%= f.label :code %>
    <%= f.text_field :code , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :expire %>
    <%= f.date_field :expire, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :import %>
    <%= f.number_field :import, min: Settings.zero, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :percent %>
    <%= f.number_field :percent,
      in: Settings.percent.minimum..Settings.percent.maximum,
      class: "form-control" %>
  </div>

  <%= f.submit yield(:request) %>
<% end %>

app/views/admin/coupons/_index.html.erb
<table class="table table-striped table-hover sortable">
  <thead>
    <tr>
      <th><%= t "coupon" %></th>
      <th><%= t "expire" %></th>
      <th><%= t "percent" %></th>
    </tr>
  </thead>
  <tbody>
    <% coupons.each do |coupon| %>
      <tr>
        <td><%= link_to coupon.code, admin_coupon_path(coupon) %></td>
        <td><%= l coupon.expire if coupon.expire %></td>
        <td><%= coupon.percent %>%</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/coupons/edit.html.erb
<% content_for :request, t("edit_coupon") %>
<% provide :title, t("edit_coupon") %>
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="add-to-cart-button"><%= t "edit_coupon" %></div>
    <div class="panel-body">
      <%= render "form", coupon: @coupon %>
    </div>
  </div>
</div>

app/views/admin/coupons/index.html.erb
<% provide :title, t("coupon") %>
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="add-to-cart-button"><%= t "coupon" %></div>
    <div class="panel-body">
      <div class="panel-footer">
        <%= link_to t("create_coupon"), new_admin_coupon_path %>
      </div>
      <%= render "index", coupons: @coupons %>
      <div class="panel-footer"><%= will_paginate @coupons %></div>
    </div>
  </div>
</div>

app/views/admin/coupons/new.html.erb
<% content_for :request, t("create_coupon") %>
<% provide :title, t("create_coupon") %>
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="add-to-cart-button"><%= t "create_coupon" %></div>
    <div class="panel-body">
      <%= render "form", coupon: @coupon %>
    </div>
  </div>
</div>

app/views/admin/coupons/show.html.erb
<% provide :title, t("order") %>
<div class="col-md-9">
  <div class="panel panel-primary">
    <div class="add-to-cart-button">
      <%= t "order" %>
    </div>
    <div class="panel-body">
      <div class="panel-footer">
        <%= link_to t("edit_coupon"), edit_admin_coupon_path(@coupon) %>
      </div>
      <table class="table table-striped table-hover">
        <tr>
          <th><%= t "product" %></th>
          <th><%= t "quantity" %></th>
          <th><%= t "price" %></th>
          <th><%= t "total_price" %></th>
          <th><%= t "time_buy" %></th>
        </tr>
        <tr>
          <td><%= @coupon.code %></td>
          <td><%= @coupon.imported %></td>
          <td><%= l @coupon.expire %></td>
          <td><%= @coupon.import %></td>
          <td><%= @coupon.percent %>%</td>
        </tr>
      </table>
    </div>
  </div>
</div>